version: 2
jobs:
    build:
      docker:
        - image: circleci/node:8.9
      steps:
        - checkout
        - run: echo "npm installing"
        - run: npm install
        - run: CI=true npm run build
    test:
      docker:
        - image: circleci/node:8.9
      steps:
        - checkout
        - run: echo "Testing"
        - run: npm install
        - run: npm run test
    hithere:
      docker:
        - image: circleci/node:8.9
      steps:
        - checkout
        - run: echo "hiiii"
workflows:
    version: 2
    build_test_and_lint:
        jobs:
          - build
          - hithere
          - test:
              requires:
                - hithere
